# PHP image CI script

stages:
- lint
- build


variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: $CI_REGISTRY_IMAGE

Docker Lint:
  stage: lint
  image: node:12
  variables:
    IMAGE_VERSION: "7.4"
  script:
    - npx dockerfilelint ./php/7.4/Dockerfile

PHP 7.4:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_VERSION: "7.4"
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull php:$IMAGE_VERSION || true
    - docker pull $NAMESPACE:$IMAGE_VERSION || true
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.4/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g goss.yml v

