name: Build Docker Image

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_VERSION: '7.2'
      NAMESPACE: 'klinktech/k-box-ci-pipeline-php'
      CI_COMMIT_SHORT_SHA: ${{github.sha}}
    steps:
    - uses: actions/checkout@v1
    # - name: Build the Docker image 
    #   run: |
    #     docker pull php:$IMAGE_VERSION || true
    #     docker pull $NAMESPACE:$IMAGE_VERSION || true
    #     docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION --build-arg VCS_REF=$CI_COMMIT_SHORT_SHA --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t $NAMESPACE:$IMAGE_VERSION -f php/7.2/Dockerfile .
    # - name: Run Goss 
    #   run: |
    #     docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss -g goss.yml v
    - name: Prepare push
      uses: azure/docker-login@v1
      # if: github.event_name == 'push'
      with:
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}
    - name: Push the Docker image
      # if: github.event_name == 'push'
      env:
        USERNAME: ${{ secrets.CI_REGISTRY_USER }}
        PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
      run: |
        cat $DOCKER_CONFIG/config.json
        docker login -u "$USERNAME" -p "$PASSWORD"
