name: Dockerfile lint

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint the Dockerfile
      run: |
        npx dockerfilelint ./php/7.4/Dockerfile
        npx dockerfilelint ./php/8.1/Dockerfile
        npx dockerfilelint ./php/8.2/Dockerfile
